FROM python:3.12-slim

WORKDIR /app

COPY requirements-frontend.txt ./requirements-frontend.txt
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY app/frontend ./app/frontend

EXPOSE 8501

CMD ["streamlit", "run", "app/frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
